<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.24" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.24" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="8.0.24" />
		<PackageReference Include="DotNetCore.CAP" Version="10.0.2-preview-287480508" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Employee.Contracts\Employee.Contracts.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
