//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkSchedule.Domain {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkSchedule.Domain.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O id é inválido..
        /// </summary>
        internal static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A matrícula deve conter {0} números..
        /// </summary>
        internal static string LengthEmployeeCode {
            get {
                return ResourceManager.GetString("LengthEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do funcionário deve conter {0} ou mais letras..
        /// </summary>
        internal static string MinLengthEmployeeName {
            get {
                return ResourceManager.GetString("MinLengthEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter {0} ou mais caracteres..
        /// </summary>
        internal static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A matrícula do funcionário só pode conter números..
        /// </summary>
        internal static string OnlyNumbersEmployeeCode {
            get {
                return ResourceManager.GetString("OnlyNumbersEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A causa é obrigatória..
        /// </summary>
        internal static string RequiredCause {
            get {
                return ResourceManager.GetString("RequiredCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O funcionário é obrigatório..
        /// </summary>
        internal static string RequiredEmployee {
            get {
                return ResourceManager.GetString("RequiredEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A matrícula do funcionário é obrigatória..
        /// </summary>
        internal static string RequiredEmployeeCode {
            get {
                return ResourceManager.GetString("RequiredEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do funcionário é obrigatório..
        /// </summary>
        internal static string RequiredEmployeeName {
            get {
                return ResourceManager.GetString("RequiredEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de final de período obrigatória..
        /// </summary>
        internal static string RequiredEndDate {
            get {
                return ResourceManager.GetString("RequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O id é obrigatório..
        /// </summary>
        internal static string RequiredGuid {
            get {
                return ResourceManager.GetString("RequiredGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter uma ou mais letras..
        /// </summary>
        internal static string RequiredLetterInPassword {
            get {
                return ResourceManager.GetString("RequiredLetterInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter uma ou mais letras em minúsculo..
        /// </summary>
        internal static string RequiredLowerCaseInPassword {
            get {
                return ResourceManager.GetString("RequiredLowerCaseInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuário é obrigatório..
        /// </summary>
        internal static string RequiredNameUser {
            get {
                return ResourceManager.GetString("RequiredNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter um ou mais números..
        /// </summary>
        internal static string RequiredNumberInPassword {
            get {
                return ResourceManager.GetString("RequiredNumberInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha é obrigatória..
        /// </summary>
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A função é obrigatória..
        /// </summary>
        internal static string RequiredRole {
            get {
                return ResourceManager.GetString("RequiredRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da função é obrigatório..
        /// </summary>
        internal static string RequiredRoleName {
            get {
                return ResourceManager.GetString("RequiredRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter um ou mais dos seguintes caracteres: [{0}].
        /// </summary>
        internal static string RequiredSpecialCharInPassword {
            get {
                return ResourceManager.GetString("RequiredSpecialCharInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de início de período obrigatória..
        /// </summary>
        internal static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter uma ou mais letras em maiúsculo..
        /// </summary>
        internal static string RequiredUpperCaseInPassword {
            get {
                return ResourceManager.GetString("RequiredUpperCaseInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome de usuário é obrigatório..
        /// </summary>
        internal static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início não pode ser posterior à data de final de período..
        /// </summary>
        internal static string StartDateCannotBeAfterEndDate {
            get {
                return ResourceManager.GetString("StartDateCannotBeAfterEndDate", resourceCulture);
            }
        }
    }
}
