//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkSchedule.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkSchedule.Domain.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe bloqueio para este servidor com mesmo período e causa..
        /// </summary>
        public static string AbsenceAlreadyExists {
            get {
                return ResourceManager.GetString("AbsenceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueio não encontrado..
        /// </summary>
        public static string AbsenceNotFound {
            get {
                return ResourceManager.GetString("AbsenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causa.
        /// </summary>
        public static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/Hora de Cadastro.
        /// </summary>
        public static string CreationTimeColumnTitle {
            get {
                return ResourceManager.GetString("CreationTimeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DateColumnTitle {
            get {
                return ResourceManager.GetString("DateColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um servidor com esta mesma matrícula..
        /// </summary>
        public static string EmployeeAlreadyExists {
            get {
                return ResourceManager.GetString("EmployeeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string EmployeeCodeColumnTitle {
            get {
                return ResourceManager.GetString("EmployeeCodeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string EmployeeNameColumnTitle {
            get {
                return ResourceManager.GetString("EmployeeNameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor não encontrado..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entra no primeiro sobreaviso?.
        /// </summary>
        public static string FirsScheduleColumnTitle {
            get {
                return ResourceManager.GetString("FirsScheduleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string IndexSign {
            get {
                return ResourceManager.GetString("IndexSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id é inválido..
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrícula deve conter {0} números..
        /// </summary>
        public static string LengthEmployeeCode {
            get {
                return ResourceManager.GetString("LengthEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do servidor deve conter {0} ou mais letras..
        /// </summary>
        public static string MinLengthEmployeeName {
            get {
                return ResourceManager.GetString("MinLengthEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter {0} ou mais caracteres..
        /// </summary>
        public static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string NameColumnTitle {
            get {
                return ResourceManager.GetString("NameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to º Sobreaviso.
        /// </summary>
        public static string NSchedule {
            get {
                return ResourceManager.GetString("NSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrícula do servidor só pode conter números..
        /// </summary>
        public static string OnlyNumbersEmployeeCode {
            get {
                return ResourceManager.GetString("OnlyNumbersEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma?.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A causa é obrigatória..
        /// </summary>
        public static string RequiredCause {
            get {
                return ResourceManager.GetString("RequiredCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O servidor é obrigatório..
        /// </summary>
        public static string RequiredEmployee {
            get {
                return ResourceManager.GetString("RequiredEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrícula do servidor é obrigatória..
        /// </summary>
        public static string RequiredEmployeeCode {
            get {
                return ResourceManager.GetString("RequiredEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do servidor é obrigatório..
        /// </summary>
        public static string RequiredEmployeeName {
            get {
                return ResourceManager.GetString("RequiredEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de final de período obrigatória..
        /// </summary>
        public static string RequiredEndDate {
            get {
                return ResourceManager.GetString("RequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id é obrigatório..
        /// </summary>
        public static string RequiredGuid {
            get {
                return ResourceManager.GetString("RequiredGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter uma ou mais letras..
        /// </summary>
        public static string RequiredLetterInPassword {
            get {
                return ResourceManager.GetString("RequiredLetterInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter uma ou mais letras em minúsculo..
        /// </summary>
        public static string RequiredLowerCaseInPassword {
            get {
                return ResourceManager.GetString("RequiredLowerCaseInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário é obrigatório..
        /// </summary>
        public static string RequiredNameUser {
            get {
                return ResourceManager.GetString("RequiredNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter um ou mais números..
        /// </summary>
        public static string RequiredNumberInPassword {
            get {
                return ResourceManager.GetString("RequiredNumberInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A função é obrigatória..
        /// </summary>
        public static string RequiredRole {
            get {
                return ResourceManager.GetString("RequiredRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da função é obrigatório..
        /// </summary>
        public static string RequiredRoleName {
            get {
                return ResourceManager.GetString("RequiredRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter um ou mais dos seguintes caracteres: [{0}].
        /// </summary>
        public static string RequiredSpecialCharInPassword {
            get {
                return ResourceManager.GetString("RequiredSpecialCharInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início de período obrigatória..
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter uma ou mais letras em maiúsculo..
        /// </summary>
        public static string RequiredUpperCaseInPassword {
            get {
                return ResourceManager.GetString("RequiredUpperCaseInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário é obrigatório..
        /// </summary>
        public static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione apenas uma linha..
        /// </summary>
        public static string SelectOneRowMessage {
            get {
                return ResourceManager.GetString("SelectOneRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser posterior à data de final de período..
        /// </summary>
        public static string StartDateCannotBeAfterEndDate {
            get {
                return ResourceManager.GetString("StartDateCannotBeAfterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro(s) removido(s) com sucesso.
        /// </summary>
        public static string SuccessDeleteMessage {
            get {
                return ResourceManager.GetString("SuccessDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro cadastrado com sucesso..
        /// </summary>
        public static string SuccessSaveMesssage {
            get {
                return ResourceManager.GetString("SuccessSaveMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso..
        /// </summary>
        public static string SuccessUpdateMessage {
            get {
                return ResourceManager.GetString("SuccessUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
